### ISSUE TITLE
getting a warning (code still executes) In drawDetails.GridGroup(x, recording = FALSE) : Group definition failed

### ISSUE THREAD

**Issue by iamYannC** [r-lib/marquee#22]
Hello. Just installed marquee_0.1.0
R version:  4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

I ran the following dummy code based on a twit:
```
library(marquee)
library(ggplot2)


my_style <- classic_style() |> 
  modify_style(
    "hl",
    color = "black", background = "green3", weight = "bold"
    
  )

ggplot(mtcars,aes(mpg,qsec))+geom_point()+
  labs(title = "This is my {.hl style}")+
  theme(plot.title = element_marquee(style = my_style))

```
and it worked but I still get the following warning:
```
Warning message:
In drawDetails.GridGroup(x, recording = FALSE) : Group definition failed
```

Not sure if it has actual impact on performance or anything..

**Comment by thomasp85** [comment]
It's a bug in the RStudio graphics device related to some of the new graphics engine features used by marquee. Besides being annoying it's inconsequential and will hopefully be solved soon
