### ISSUE TITLE
Set default's `element_marquee()`'s margin to 0?

### ISSUE THREAD

**Issue by teunbrand** [r-lib/marquee#23]
Hi Thomas,

I've been playing around a bit and found it surprising that `element_marquee()` comes with a default (bottom) margin.
I'm aware that `element_marquee(margin)` gets funneled to `style(padding)`, so the only reasonable way to remove it is to edit the style.

For example, if you have tiny keys, `element_text()` legend text is tightly packed:

``` r
library(ggplot2)
library(marquee)

p <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  theme(legend.key.size = unit(0, "cm"))

p
```

![](https://i.imgur.com/1qeijc9.png)

However, if you use `element_marquee()` there is a large bottom margin. At first I was confused because I thought it was the `vjust` that was off, but it turned out it is the margin.

``` r
p + theme(legend.text = element_marquee())
```

![](https://i.imgur.com/gXVSo4m.png)

My proposal is to let the `element_grob.element_marquee()` adjust elements where `style = NULL` to discard the bottom margin, so that `style(padding)` is the only determinant of the spacing around the text.

``` r
p + theme(legend.text = element_marquee(
  style = classic_style() |> modify_style("base", margin = trbl(0))
))
```

![](https://i.imgur.com/GSBoH9M.png)

<sup>Created on 2024-06-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Happy to submit a PR if you agree.

**Comment by thomasp85** [comment]
I don't think this is the best approach since it would adversely affect elements that contains multiple paragraphs (they would not get any vertical spacing between them).

honestly, I thought I had solved this - let me check

**Comment by teunbrand** [comment]
> affect elements that contains multiple paragraphs

That makes sense to me, but any other way of turning off the additional space for single paragraphs (or the last paragraph) would be swell as well.

**Comment by thomasp85** [comment]
yeah, I'm looking into it now

**Comment by thomasp85** [comment]
sadly, I opened a pandoras box of un-considered margin collapsing situations
