### ISSUE TITLE
Textbox clipping with {ragg}

### ISSUE THREAD

**Issue by teunbrand** [r-lib/marquee#25]
Hi Thomas,

I'm not sure wether this issue belongs to {ragg} or {marquee}, but since you maintain both it should at least be adressed to the correct person 😅 
When adding a textbox through the style and render the grob with {ragg}, I find sometimes the text appears to be clipped to the box.
In the example below, one'd expect `"I'm"` and `"ith padding"` to be rendered as well.

``` r
library(marquee)

s <- classic_style() |>
  modify_style("block", background = "grey50", padding = trbl(rem(1)))

grob <- marquee_grob("I'm a {.block textbox} with padding", s)

tmp <- tempfile(fileext = ".png")
ragg::agg_png(tmp, height = 50)
grid::grid.newpage()
grid::grid.draw(grob)
dev.off()
#> png 
#>   2

knitr::include_graphics(tmp)
```

<img src="https://i.imgur.com/PdQRZY0.png" width="480" />

<sup>Created on 2024-06-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
Do you have an updated ragg installation? Pretty sure this was fixed by the latest release

**Comment by teunbrand** [comment]
Argh, yes you're right! I do apologise for the noise
