### ISSUE TITLE
margins change when adding element_marquee to plot titles

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/marquee#27]
```
library(tidyverse)
library(palmerpenguins)
library(marquee)

p1 <- penguins |>
  ggplot() +
  geom_histogram(aes(x = bill_depth_mm)) +
  labs(
    title = "Pygoscelis penguin bill depths",
    subtitle = "Adelie, Chinstrap, and Gentoo species",
  ) 

p2 <- p1 + 
  theme(plot.title = marquee::element_marquee()) +
  theme(plot.subtitle = marquee::element_marquee())

p1

p2
```
<img width="447" alt="image" src="https://github.com/r-lib/marquee/assets/55065152/15be8f08-8ba8-44ac-b4db-0209b9a82c2b">

<img width="452" alt="image" src="https://github.com/r-lib/marquee/assets/55065152/1ae3d808-0d84-455e-aa29-e7df05bc0407">

**Comment by thomasp85** [comment]
I think this is fixed in dev. I did some tweaks to the margin collapsing based on similar feedback

**Comment by davidhodge931** [comment]
Thanks! Ddev version margins look really good :)
