### ISSUE TITLE
font looks slightly different, particularly when article is a github website

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/marquee#29]
Does the font (or font spacing) change when using `element_marquee()`? 

Maybe it looks ever-so-slightly different in the console and in a Rmd article - but it looks very different when the article is pushed to github.

Console without marquee
<img width="404" alt="image" src="https://github.com/r-lib/marquee/assets/55065152/59d85ed7-6c6f-474d-8264-ab7882c38b44">

Console with marquee
<img width="404" alt="image" src="https://github.com/r-lib/marquee/assets/55065152/81e04de5-d87e-4d8d-b365-08159c3d8061">

pkdown Rmd article in local with marquee
<img width="424" alt="image" src="https://github.com/r-lib/marquee/assets/55065152/d401f5c9-7c17-414d-aa9e-a2e9dbbc2139">
 
pkdown Rmd article on github built website with marquee
<img width="404" alt="image" src="https://github.com/r-lib/marquee/assets/55065152/0ef693f2-e749-46b8-9a53-8ad4df0b10dc">

I noticed this in this blog as well
https://nrennie.rbind.io/blog/coloured-text-legend-ggplot-ggtext-marquee/

**Comment by thomasp85** [comment]
Thanks for this. It is somewhat expected and impossible to guard against. Marquee uses textshaping and systemfonts to find and place glyphs which may be different from how the graphics device works for regular text.

Can you tell me which graphics devices are in effect in the above plots?

**Comment by davidhodge931** [comment]
Thanks for the explanation.

If that is the case, it'd be cool to have a function to convert all element_text elements in a theme to element_marquee, so the font within the plot looked 100% consistent.

The global settings had Cairo png

**Comment by thomasp85** [comment]
yes, especially Cairo will look a bit different. Emphasised if you are using the font aliases as these may map to a different font entirely. If you use the ragg devices it should all look pretty similar

**Comment by thomasp85** [comment]
There is now a `marquefy_theme()` function as well as a bunch of fixes to make justification and margins of element_marquee more in line with element_text

**Comment by davidhodge931** [comment]
Awesome, thanks!!

**Comment by davidhodge931** [comment]
Something that just came to mind.. I wonder whether it'll get slightly confusing, if you spell `marquefy` with one `e` here.

A couple of other ideas are:

* `as_marquee`
* `marquee_theme`

This function will be super useful, thanks!

**Comment by teunbrand** [comment]
Wouldn't it more ideal if `+ theme(text = element_marquee())` would just work?

**Comment by thomasp85** [comment]
I'm not sure that is possible... How would you, as user, then have a root level marquee element but set a specific element to `element_text()`

**Comment by teunbrand** [comment]
For sure it isn't currently possible. But I think you could either add an `inherit.class` argument or have an `element_placeholder()` that just adopts the parent's class.

**Comment by thomasp85** [comment]
We can muse about this in the ggplot2 repo - this isn't really up to marquee :-)
