### ISSUE TITLE
Text not rendering

### ISSUE THREAD

**Issue by RoyalTS** [r-lib/marquee#30]
The example [from the docs](https://marquee.r-lib.org/reference/element_marquee.html)

```r
library(ggplot2)
library(marquee)
p <- ggplot(mtcars) +
  geom_point(aes(mpg, disp)) +
  labs(title = "A {.red *marquee*} title\n* Look at this bullet list\n\n* great, huh?") +
  theme_gray(base_size = 6) +
  theme(title = element_marquee())

plot(p)
```

Results in a plot in which the title is not rendered at all:

<img width="595" alt="Screenshot 2024-06-08 at 17 01 35" src="https://github.com/r-lib/marquee/assets/702580/d51f54fd-9cdc-4c75-bdd2-9bf00ba68fc4">

**Comment by thomasp85** [comment]
My guess is that it is a graphics device issue. What device and version are you using?

**Comment by RoyalTS** [comment]
Ah, indeed. Was using the default device in Rstudio. The whole thing works if using RAG.

That does seem to be mangling my ggplot theme's font though :|

**Comment by thomasp85** [comment]
Can you please open a new issue with a reprex for that?

**Comment by RoyalTS** [comment]
Filed an issue [here](https://github.com/r-lib/ragg/issues/168) – I hope that was the right place for it.
