### ISSUE TITLE
Support superscript and subscript

### ISSUE THREAD

**Issue by holnburger** [r-lib/marquee#37]
Superscript and subscript are not part of commonscript as far as I know (https://spec.commonmark.org/0.31.2/) but it's supported in ggtext element_markdown via `^superscript^` or `<sup></sup>`. Sadly that's not the case for marquee. 
It would be great if marquee also supports superscript and subscript. In the meantime I used UTF-8 variants of superscript numbers (https://www.compart.com/de/unicode/U+00B3)

**Comment by thomasp85** [comment]
There are already classes for it in the main style - just use {.sub ...} or {.sup ...}
